# -*- coding: utf-8 -*-
"""WOW_DataCleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uqhy0sxMnkmx9HqhIzvtkr_ZGe3Mrlty
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O 

# read in the San Francisco building permits data
wow = pd.read_csv("wonders_of_world.csv")

# set seed for reproducibility
np.random.seed(0)

wow.sample(5)

# Calculate total number of cells in dataframe
totalCells = np.product(wow.shape)

# Count number of missing values per column
missingCount = wow.isnull().sum()

# Calculate total number of missing values
totalMissing = missingCount.sum()

# Calculate percentage of missing values
print("The Wonders of World Dataset contains", round(((totalMissing/totalCells) * 100), 2), "%", "missing values.")

missingCount[['Name','Type','Latitude','Longitude','Location','Wikipedia link','Picture link','Build in year']]

print("Percentage of missing data in Build in year column =", (round(((missingCount['Build in year'] / wow.shape[0]) * 100), 2)))

wow.dropna()

wowCleanCols = wow.dropna(axis=1)
wowCleanCols.head()

print("Columns in original dataset: %d \n" % wow.shape[1])
print("Columns with NA's dropped: %d" % wowCleanCols.shape[1])